[package]
name = "game-of-life"
version = "0.1.0"
authors = ["chris"]

include = [
	"src/**/*.rs"
]

[dependencies]
kiss3d = { git = "https://github.com/sebcrozet/kiss3d" }
glfw-sys = "3.1.3"
nalgebra = "*"
time = "*"
rand = "*"
